= Abkürzungsverzeichnis

#table(columns: (23mm, 1fr), stroke: none, inset: (y: 1.5pt, x: 0pt),
[ACK], [Acknowledgement],
[API], [Application Programming Interface],
[ASCII], [American Standard Code for Information Interchange],
[BOR], [Brown-out Reset],
[CDC], [Communications Device Class],
[CMSIS], [Cortex Microcontroller Software Interface Standard],
[CPU], [Central Processing Unit],
[CRC], [Cyclic Redundancy Check],
[CSV], [Comma-Separated Values],
[DNS], [Domain Name System],
[GND], [Ground],
[GPIO], [General Purpose Input/Output],
[HSI], [High-Speed Internal Oscillator],
[HTTP(S)], [Hypertext Transfer Protocol (Secure)],
[I2C], [Inter-Integrated Circuit],
[ICMP], [Internet Control Message Protocol],
[I/O], [Input/Output],
[IWDG], [Independent Watchdog],
[JSON], [JavaScript Object Notation],
[LCD], [Liquid Crystal Display],
[LSI], [Low-Speed Internal Oscillator],
[NACK], [Not Acknowledged],
[NMEA], [National Marine Electronics Association],
[NTP], [Network Time Protocol],
[PID], [Process Identifier],
[PVD], [Programmable Voltage Detector],
[RCC], [Reset and Clock Control],
[RMC], [Recommended Minimum Specific GNSS Data],
[RTC], [Real-Time Clock],
[RX/TX], [Receive/Transmit],
[SCL], [Serial Clock],
[SDA], [Serial Data],
[SHA-256], [Secure Hash Algorithm 256 Bit],
[TCP], [Transmission Control Protocol],
[TLS], [Transport Layer Security],
[UART], [Universal Asynchronous Receiver/Transmitter],
[USB], [Universal Serial Bus],
[VIN], [Voltage Input],
[WCET], [Worst-Case Execution Time],
[WDT], [Watchdog Timer],
[WMO], [World Meteorological Organization],
[XOR], [Exclusive OR],
)
