#import "../layout.typ": *

= Zusammenfassung

Diese Bachelorarbeit untersucht Watchdog- und Recovery-Strategien an einem heterogenen eingebetteten System aus Raspberry Pi und dem Mikrocontroller STM32L432KC. Als Testanwendung erfasst der Raspberry Pi Positionsdaten eines Binghe VK-162 USB-GPS-Empfängers, ruft Wetterdaten für den ermittelten Standort ab und überträgt einen strukturierten Status über eine serielle UART-Verbindung (Universal Asynchronous Receiver/Transmitter). Der STM32 prüft die Datenintegrität, stellt Nutz- und Fehlerzustände auf einer Flüssigkristallanzeige (Liquid Crystal Display, LCD) dar und überwacht die Gesundheitszustände seiner Komponenten mit einem lokalen Supervisor.

Die Architektur kombiniert mehrere Schutzebenen: Protokollvalidierung, lokale Komponenten-Recovery, degradierte Betriebsmodi, getrennte systemd-Dienste mit Restart-Policy und Service-Watchdog, den Independent Watchdog (IWDG) des STM32 sowie den Hardware-Watchdog des Raspberry Pi. Die Zuordnung folgt dem Prinzip, die kleinste Recovery-Ebene zu verwenden, die den jeweiligen Fehler zuverlässig beseitigt.

Untersucht wurden ein blockierter HTTPS-Wetterdatenpfad, GPS- und UART-Unterbrechungen, Dienst-Hänger und -Abstürze, ein STM32-Firmware-Hänger, fehlerhafte UART-Nachrichten, ein Displayausfall, Spannungsverlust, Unterspannung und ein Kernel-Hänger. Die jeweils fünfmal ausgeführten risikoarmen funktionalen Testfälle waren in allen Durchläufen erfolgreich. Beim blockierten HTTPS-Wetterdatenpfad, der keine Unterscheidung zwischen Netz- und Wetterdienstfehler erlaubt, betrugen Fehlerweitergabe und Recovery im Mittel 7,36 s beziehungsweise 10,10 s. Ein STM32-Firmware-Hänger wurde durch den IWDG in 5,70 s bis zur Rückkehr in den Anwendungsmodus behoben. Ein hängender GPS-Dienst benötigte im Mittel 28,46 s, ein abgestürzter Dienst dagegen 5,76 s. Nach vollständigem Spannungsverlust betrug die extern gemessene Netzwerk-Nichtverfügbarkeit im Mittel 32,33 s.

Der ergänzende Unterspannungstest am VIN-Eingang der NUCLEO-L432KC-Platine zeigte in fünf von fünf Durchläufen denselben stufenweisen Funktionsverlust: Normalbetrieb bei 8–6 V, verringerte LCD-Hintergrundbeleuchtung bei 5 V, Ausfall der Zeichendarstellung mit STM32-Neustart bei 4 V, vollständigen LCD-Ausfall mit erneutem Neustart bei 3 V und vollständigen Stillstand des STM32 bei 2 V. Beim Raspberry Pi belegte der Statuswert 0x50005 bei einer am Labornetzteil eingestellten Spannung von 4,50 V gleichzeitig aktive Unterspannung und Drosselung. Die Ergebnisse zeigen, dass eine abgestufte Fehlerbehandlung unnötige Gesamtneustarts vermeidet und in den durchgeführten Versuchen auch schwere Hänger behandeln konnte. Als Grenzen verbleiben insbesondere die manuelle Fehlerinjektion, das Hot-Start-Verhalten des GPS-Empfängers sowie die fehlende Messung der internen Versorgungsschienen und Reset-Ursachen während des Unterspannungstests.
